// ngõ vào
NET "clk_50m" LOC = "C9" | IOSTANDARD = LVCMOS33 ;
NET "clk_50m" CLOCK_DEDICATED_ROUTE = FALSE ;
NET "reset" LOC = "L13" | IOSTANDARD = LVTTL | PULLUP ;
NET "a" LOC = "L14" | IOSTANDARD = LVTTL | PULLUP ;
NET "b" LOC = "H18" | IOSTANDARD = LVTTL | PULLUP ;
// ngõ ra
NET "clk_1hz" LOC = "C11" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "y1" LOC = "E12" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "y0" LOC = "F12" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "tt_ht<1>" LOC = "F9" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "tt_ht<0>" LOC = "E9" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
