// ngõ vào
NET "clk_50m" LOC = "C9" | IOSTANDARD = LVCMOS33 ;
NET "clk_50m" CLOCK_DEDICATED_ROUTE = FALSE ;
NET "reset" LOC = "L13" | IOSTANDARD = LVTTL | PULLUP ;
NET "w" LOC = "L14" | IOSTANDARD = LVTTL | PULLUP ;
// ngõ ra
NET "z" LOC = "F12" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "clk_1hz" LOC = "F9" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "tt_ht<0>" LOC = "E11" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
NET "tt_ht<1>" LOC = "F11" | IOSTANDARD = LVTTL | SLEW = SLOW | DRIVER = 8 ;
